import "./vendors/swiper.min.js";
import "./vendors/www-widgetapi.js";
import "./modules/heightControl.js";
import headerScroll from "./modules/headerScroll.js";
import mobileMenuHandler from "./modules/mobileMenuHandler.js";
import offerSwiper from "./modules/offerSwiper.js";
import newsSwiper from "./modules/newsSwiper.js";
import newsVideoHandler from "./modules/newsVideoHandler.js";
import footerMenuHandler from "./modules/footerMenuHandler.js";
import categoryGoodsSwiper from "./modules/categoryGoodsSwiper.js";
import regionSearchHandler from "./modules/regionSearchHandler.js";
import mapPopupHandler from "./modules/mapPopupHandler.js";
import cityFilterHandler from "./modules/cityFilterHandler.js";
import dealersListHandler from "./modules/dealersListHandler.js";
import goodsSwiper from "./modules/goodsSwiper.js";
import zIndexDelay from "./modules/zIndexDelay.js";
import goodsFilterHandler from "./modules/goodsFilterHandler.js";
import productSwiper from "./modules/productSwiper.js";
import productDetailsHandler from "./modules/productDetailsHandler.js";
import popupHandler from "./modules/popupHandler.js";
import goodSearchHandler from "./modules/goodSearchHandler.js";

headerScroll();
popupHandler();
mobileMenuHandler();
offerSwiper();
newsSwiper();
newsVideoHandler();
footerMenuHandler();
categoryGoodsSwiper();
mapPopupHandler();
regionSearchHandler();
cityFilterHandler();
dealersListHandler();
goodsSwiper();
zIndexDelay();
goodsFilterHandler();
productSwiper();
productDetailsHandler();
goodSearchHandler();
